name: Version, build, publish

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-publish.yml'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  workflow_dispatch:

jobs:

  # Determine the next version from commits (if any)
  semantic_release_dry_run:
    name: Semantic Release (dry run)
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install node.js (npm)
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18

      # Install packages
      - run: npm install

      # Run semantic release to determine the next version
      - run: npx semantic-release --dry-run
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Output the new version and previous version
    outputs:
      version: ${{ steps.semantic_release.outputs.version }}
      previous: ${{ steps.semantic_release.outputs.previous }}

  # Build & test if a new version is available
  test_rust:
    name: Build Rust
    needs: semantic_release_dry_run
    if: needs.semantic_release_dry_run.outputs.version != ''
    runs-on: ubuntu-latest
    env:
      V_VERSION: ${{ needs.semantic_release_dry_run.outputs.version }}
      V_PREVIOUS: ${{ needs.semantic_release_dry_run.outputs.previous }}
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Run the versioning script to update the Cargo.toml file
      - run: sed -i "s/^version = .*$/version = \"$V_VERSION\"/" Cargo.toml

      # Run all tests
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --release --all-features

      # Save the modified Cargo.toml / Cargo.lock file with the updated version
      - uses: actions/upload-artifact@v3
        with:
          name: semantic-release-cargo
          path: |
            Cargo.toml
            Cargo.lock
          retention-days: 1

  semantic_release_publish:
    name: Publish to GitHub
    needs: test_rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Download the modified Cargo files
      - uses: actions/download-artifact@v3
        with:
          name: semantic-release-cargo

      # Run and publish
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - run: npm install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload_crates:
    name: Publish to crates.io
    needs: semantic_release_publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: semantic-release-cargo
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish --allow-dirty --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
