name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/**'
  workflow_dispatch:

jobs:

  # Determine the next version from commits (if any)
  semantic_release_dry_run:
    name: Semantic Release (dry run)
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install node.js (npm)
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18

      # Install packages
      - run: npm install

      # Run semantic release to determine the next version
      - run: npx semantic-release --dry-run
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Output the new version and previous version
    outputs:
      version: ${{ steps.semantic_release.outputs.version }}
      previous: ${{ steps.semantic_release.outputs.previous }}

  # Build the documentation
  build_docs:
    name: Build documentation
    needs: semantic_release_dry_run
    runs-on: ubuntu-latest
    env:
      V_VERSION: ${{ needs.semantic_release_dry_run.outputs.version }}
      V_PREVIOUS: ${{ needs.semantic_release_dry_run.outputs.previous }}
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            docs

      # Install node.js (npm)
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18

      # Build the documentation
      - name: Build documentation
        run: |
          cd ./docs
          export VERSION="${V_VERSION:-$V_PREVIOUS}"
          echo "$VERSION"
          npm install
          npm run generate

      # Deploy to the gh-pages branch
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/.output/public
